### ISSUE TITLE
Pre-provision karaf after installation of AET bundles

### ISSUE THREAD

**Issue by karoldrazek** [Skejven/aet-docker#9]
Right now karaf is pre-provisioned with only based bundles and dependencies.
The AET bundles are installed afterwards.

Please kindly consider moving pre-provisioning or adding second pre-provisioning after installation of AET bundles.

**Comment by Skejven** [comment]
@karoldrazek 
thanks for suggesting this improvement.

Unfortunately it is not so easy to warmup AET bundles in the same fashion as [basic Karaf and features dependencies](https://github.com/Skejven/aet-docker/blob/0.9.0/karaf/Dockerfile#L53).

Some of the AET bundles require connection to external services (e.g. ActiveMQ or MongoDB).
Without the successful connection, bundle will not be started and Karaf startup generally fails.

In the current (`0.9.0`) version of the AET Docker images OSGi configuration is a separate layer and is not coupled with the Karaf image (it is stored in the volumen and delivered to the image after it the build). Warming up AET bundles would require delivering some basic configs, that might be cached and cause problems with custom configs usage when deploying image.

**Comment by Skejven** [comment]
Hi, finally I had some time to fix it - see #27 .
